VacationRegister/Models/Leave.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Security.Cryptography;

namespace VacationRegister.Models
{
    public class Leave
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int LeaveId { get; set; }
        
        [Required(ErrorMessage = "You have to enter a start date")]
        [DataType(DataType.Date)]
        [Display(Name = "Start date")]
        public DateTime StartDate { get; set; }
        
        [Required(ErrorMessage = "You have to enter a end date")]
        [DataType(DataType.Date)]
        [Display(Name = "End date")]
        public DateTime EndDate { get; set; }
        
        [Display(Name = "Days")]
        public double? DiffInDays 
        { 
            get { return (EndDate - StartDate).TotalDays; }
        }

        [Display(Name = "Notes")]
        [StringLength(120)]
        public string? LeaveNotes { get; set; }
        
        private DateTime _Created = DateTime.Now;
        [Display(Name = "Created")]
        public DateTime CreateDate { get { return _Created; } set { _Created = value; } }
        
        [ForeignKey("LeaveType")]
        [Display(Name = "Type of leave")]
        [Required(ErrorMessage = "You have to select type of leave")]
        public int FkLeaveTypeId { get; set; }
        public LeaveType? LeaveType { get; set; }
       
        [ForeignKey("Employee")]
        [Display(Name = "Employee")]
        [Required(ErrorMessage = "You have to choose a Employee")]
        public int FkEmpId { get; set; }
        public Employee? Employee { get; set; }

        
    }
}

VacationRegister/Models/LeaveType.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VacationRegister.Models
{
    public class LeaveType
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int LeaveTypeId { get; set; }
        [Display(Name = "Type of Leave")]
        [StringLength(40)]
        public string TypeofLeave { get; set; }
        [Display(Name = "Leave Description")]
        [StringLength(100)]
        public string LeaveDescr { get; set; }
        public virtual ICollection<Leave>? Leaves { get; set; }
    }
}

VacationRegister/Controllers/LeavesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using VacationRegister.Data;
using VacationRegister.Models;

namespace VacationRegister.Controllers
{
    public class LeavesController : Controller
    {
        private readonly VacRegDbContext _context;

        public LeavesController(VacRegDbContext context)
        {
            _context = context;
        }

        // GET: Leaves
        public async Task<IActionResult> Index(string searchString, DateTime? start, DateTime? end, string sortOrder, string currentFilter, int? pageNumber)
        {
            if (_context.Leaves == null)
            {
                return Problem("Entity set 'VacRegDbContext.Leaves' is null.");
            }

            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParam"] = String.IsNullOrEmpty(sortOrder) ? "firstName" : "lastName";
            ViewData["DateSortParam"] = sortOrder == "Date" ? "Date" : "" ;
            
            if (searchString!= null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;
            var leaves = from l in _context.Leaves
                             .Include(l => l.Employee)
                             .Include(l => l.LeaveType)
                             select l;

            if (!String.IsNullOrEmpty(searchString))
            {
                leaves = leaves.Where(s => s.Employee.FirstName!.Contains(searchString)
                                    || s.Employee.LastName!.Contains(searchString));
            }

            if (start.HasValue)
            {
                leaves = leaves.Where(l => l.CreateDate >= start && l.CreateDate <= end);
            }
            switch (sortOrder)
            {
                case "firstName":
                    leaves = leaves.OrderBy(l => l.Employee.FirstName);
                    break;
                case "Date":
                    leaves = leaves.OrderBy(l => l.StartDate);
                    break;
                case "lastName":
                    leaves = leaves.OrderBy(l => l.Employee.LastName);
                    break;
                default:
                    leaves = leaves.OrderByDescending(l => l.StartDate);
                    break;
            }
            int pageSize = 6;
            return View(await PaginatedList<Leave>.CreateAsync(leaves.AsNoTracking(), pageNumber ?? 1, pageSize));


            //return View(await leaves.AsNoTracking().ToListAsync());


        }

        // GET: Leaves/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leave = await _context.Leaves
                .Include(l => l.Employee)
                .Include(l => l.LeaveType)
                .FirstOrDefaultAsync(m => m.LeaveId == id);
            if (leave == null)
            {
                return NotFound();
            }

            return View(leave);
        }

        // GET: Leaves/Create
        public IActionResult Create()
        {
            ViewData["FkEmpId"] = new SelectList(_context.Employees, "EmpId", "Fullname");
            ViewData["FkLeaveTypeId"] = new SelectList(_context.LeaveTypes, "LeaveTypeId", "TypeofLeave");
            return View();
        }

        // POST: Leaves/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LeaveId,StartDate,EndDate,LeaveNotes,CreateDate,FkLeaveTypeId,FkEmpId")] Leave leave)
        {
            if (ModelState.IsValid)
            {
                _context.Add(leave);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkEmpId"] = new SelectList(_context.Employees, "EmpId", "FirstName", leave.FkEmpId);
            ViewData["FkLeaveTypeId"] = new SelectList(_context.LeaveTypes, "LeaveTypeId", "LeaveTypeId", leave.FkLeaveTypeId);
            return View(leave);
        }

        // GET: Leaves/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leave = await _context.Leaves.FindAsync(id);
            if (leave == null)
            {
                return NotFound();
            }
            ViewData["FkEmpId"] = new SelectList(_context.Employees, "EmpId", "FirstName", leave.FkEmpId);
            ViewData["FkLeaveTypeId"] = new SelectList(_context.LeaveTypes, "LeaveTypeId", "LeaveTypeId", leave.FkLeaveTypeId);
            return View(leave);
        }

        // POST: Leaves/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LeaveId,StartDate,EndDate,LeaveNotes,CreateDate,FkLeaveTypeId,FkEmpId")] Leave leave)
        {
            if (id != leave.LeaveId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(leave);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LeaveExists(leave.LeaveId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkEmpId"] = new SelectList(_context.Employees, "EmpId", "FirstName", leave.FkEmpId);
            ViewData["FkLeaveTypeId"] = new SelectList(_context.LeaveTypes, "LeaveTypeId", "LeaveTypeId", leave.FkLeaveTypeId);
            return View(leave);
        }

        // GET: Leaves/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leave = await _context.Leaves
                .Include(l => l.Employee)
                .Include(l => l.LeaveType)
                .FirstOrDefaultAsync(m => m.LeaveId == id);
            if (leave == null)
            {
                return NotFound();
            }

            return View(leave);
        }

        // POST: Leaves/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var leave = await _context.Leaves.FindAsync(id);
            if (leave != null)
            {
                _context.Leaves.Remove(leave);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LeaveExists(int id)
        {
            return _context.Leaves.Any(e => e.LeaveId == id);
        }
    }
}

VacationRegister/Views/Leaves/Create.cshtml
@model VacationRegister.Models.Leave

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Leave</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FkEmpId" class="control-label"></label>
                <select asp-for="FkEmpId" class ="form-control" asp-items="ViewBag.FkEmpId">
                    <option value="">-- Select Employee --</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="FkLeaveTypeId" class="control-label"></label>
                <select asp-for="FkLeaveTypeId" class="form-control" asp-items="ViewBag.FkLeaveTypeId">
                    <option value="">-- Select Type --</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeaveNotes" class="control-label"></label>
                <input asp-for="LeaveNotes" class="form-control" />
                <span asp-validation-for="LeaveNotes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-outline-primary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VacationRegister/Views/Leaves/Delete.cshtml
@model VacationRegister.Models.Leave

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this leave request?</h3>
<div>
    <h4>Leave</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveNotes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeaveNotes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeaveType.TypeofLeave)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee.Fullname)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="LeaveId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-primary">Back to List  </a>
    </form>
</div>

VacationRegister/Views/Leaves/Details.cshtml
@model VacationRegister.Models.Leave

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Leave</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LeaveType.TypeofLeave)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveNotes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeaveNotes)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee.Fullname)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DiffInDays)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DiffInDays)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.LeaveId" class="btn btn-success">Edit</a> |
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</div>

VacationRegister/Views/Leaves/Edit.cshtml
@model VacationRegister.Models.Leave

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Leave</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LeaveId" />
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeaveNotes" class="control-label"></label>
                <input asp-for="LeaveNotes" class="form-control" />
                <span asp-validation-for="LeaveNotes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreateDate" class="control-label"></label>
                <input asp-for="CreateDate" class="form-control" />
                <span asp-validation-for="CreateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FkLeaveTypeId" class="control-label"></label>
                <select asp-for="FkLeaveTypeId" class="form-control" asp-items="ViewBag.FkLeaveTypeId"></select>
                <span asp-validation-for="FkLeaveTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FkEmpId" class="control-label"></label>
                <select asp-for="FkEmpId" class="form-control" asp-items="ViewBag.FkEmpId"></select>
                <span asp-validation-for="FkEmpId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" /> |
                <a asp-action="Index" class="btn btn-primary">Back to List</a>
            </div>
        </form>
    </div>
</div>

@* <div>
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</div> *@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VacationRegister/Views/Leaves/Index.cshtml
@model PaginatedList<VacationRegister.Models.Leave>

@{
    ViewData["Title"] = "Index";
}

<h1>Leave requests</h1>

<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
</p>
 <form asp-controller="Leaves" asp-action="Index" method="get">
    <div>
        <p>
            <input type="text" name="SearchString" placeholder="Enter first or last name" value="@ViewData["CurrentFilter"]" />
            <input type="date" name="start" />
            <input type="date" name="end" />
            <input type="submit" value="Filter" class="btn btn-primary" /> 
        </p>
    </div>
</form>
<table class="table table-bordered table-hover">
    <thead class="table-success">
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Employee</a>
            </th>
            <th>
                Type of leave
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["DateSortParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">From</a>
            </th>
            <th>
                To
            </th>
            <th>
                Notes
            </th>
            <th>
                Days
            </th>
            <th>
                Created
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Employee.Fullname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LeaveType.TypeofLeave)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LeaveNotes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiffInDays)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateDate)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.LeaveId" class="btn btn-primary btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="Edit!"><i class="bi bi-pencil-square"></i></a>
                    <a asp-action="Details" asp-route-id="@item.LeaveId" class="btn btn-success btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="Details"><i class="bi bi-info-square"></i></a> 
                    <a asp-action="Delete" asp-route-id="@item.LeaveId" class="btn btn-danger btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="Delete"><i class="bi bi-trash"></i></a> 
            </td>
        </tr>
}
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>
<a asp-action="Index" class="btn btn-outline-primary">Back to Full List</a>